# Generated by Django 3.1.4 on 2021-03-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_banco', models.CharField(max_length=20, verbose_name='Código do Banco')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Banco',
                'ordering': ['codigo_banco'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencias', to='banco.banco', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Agência',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80, verbose_name='Número')),
                ('saldo', models.DecimalField(decimal_places=10, default=0.0, max_digits=19, verbose_name='Saldo')),
                ('tipo', models.CharField(choices=[('FISICA', 'Pessoa física'), ('JURIDICA', 'Pessoa jurídica')], max_length=15, verbose_name='Tipo')),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='banco.agencia', verbose_name='Agência')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='banco.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Conta',
                'ordering': ['numero'],
                'unique_together': {('cliente', 'tipo', 'agencia')},
            },
        ),
    ]
