# Generated by Django 3.1.4 on 2021-03-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_auto_20210322_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Saldo'),
        ),
    ]
