# Generated by Django 3.1.4 on 2021-03-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_auto_20210323_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='codigo_agencia',
            field=models.CharField(default=1, max_length=20, verbose_name='Código da Agência'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='agencia',
            unique_together={('codigo_agencia', 'banco')},
        ),
    ]
